spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/movie
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: eunulee03@gmail.com
    password: caffbdsabeyqtawr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  jwt:
    secret: emVyb2Jhc2UtcHJvamVjdC1tb3ZpZS1ib2FyZC1qd3Qtc2VjcmV0LWtleS1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWtleQo=

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.board.movie: DEBUG
  file:
    name: myapp.log
  pattern:
    console:
      dateformat: yyyy-MM-dd HH:mm:ss
      logformat: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"